Add current-route recipe

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,6 +31,7 @@ before_cache:
   - rm -rfv $CABALHOME/packages/head.hackage
 matrix:
   include:
+<<<<<<< HEAD
     - compiler: ghcjs-8.4
       addons: {"apt":{"sources":["hvr-ghc"],"packages":["cabal-install-3.0"]}}
     - compiler: ghc-8.6.5
@@ -65,12 +66,33 @@ before_install:
   - if $GHCJS ; then sudo apt-get install -y ghc-8.4.4 ; fi
   - if $GHCJS ; then PATH="/opt/ghc/8.4.4/bin:$PATH" ; fi
   - HCPKG="$HC-pkg"
+=======
+    - compiler: "ghc-8.6.3"
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.6.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.4.4"
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.2"
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
+
+before_install:
+  - HC=/opt/ghc/bin/${CC}
+  - HCVER=$(echo "$TRAVIS_COMPILER" | sed 's/ghc-//')
+  - echo $HCVER
+  - HCPKG=${HC/ghc/ghc-pkg}
+>>>>>>> dfb80faa... Add current-route recipe
   - unset CC
   - CABAL=/opt/ghc/bin/cabal
   - CABALHOME=$HOME/.cabal
   - export PATH="$CABALHOME/bin:$PATH"
+<<<<<<< HEAD
   - TOP=$(pwd)
   - "HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\\d+)\\.(\\d+)\\.(\\d+)(\\.(\\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')"
+=======
+  - ROOTDIR=$(pwd)
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+>>>>>>> dfb80faa... Add current-route recipe
   - echo $HCNUMVER
   - CABAL="$CABAL -vnormal+nowrap+markoutput"
   - set -o pipefail
@@ -99,6 +121,7 @@ install:
   - echo $GHCJS
   - TEST=--enable-tests
   - BENCH=--enable-benchmarks
+<<<<<<< HEAD
   - HEADHACKAGE=false
   - rm -f $CABALHOME/config
   - |
@@ -171,6 +194,63 @@ install:
     echo "allow-newer:  openssl-streams-1.2.2.0:network"   >> cabal.project
     echo "optimization: False"                             >> cabal.project
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(cookbook-basic-auth|cookbook-basic-streaming|cookbook-curl-mock|cookbook-db-postgres-pool|cookbook-db-sqlite-simple|cookbook-file-upload|cookbook-generic|cookbook-https|cookbook-pagination|cookbook-structuring-apis|cookbook-testing|cookbook-using-custom-monad|cookbook-using-free-client|servant|servant-client|servant-client-core|servant-conduit|servant-docs|servant-foreign|servant-http-streams|servant-jsaddle|servant-machines|servant-pipes|servant-server|tutorial)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+=======
+  - GHCHEAD=${GHCHEAD-false}
+  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export CABALHOME=$APPDATA/cabal; else export CABALHOME=$HOME/.cabal; fi
+  - travis_retry ${CABAL} update -v
+  - sed -i.bak 's/^jobs:/-- jobs:/' $CABALHOME/config
+  - rm -fv cabal.project cabal.project.local
+  - "sed -i.bak 's/-- ghc-options:.*/ghc-options: -j2/' $CABALHOME/config"
+  - grep -Ev -- '^\s*--' $CABALHOME/config | grep -Ev '^\s*$'
+  - rm -f cabal.project
+  - touch cabal.project
+  - "printf 'packages: \"servant\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-client\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-client-core\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-http-streams\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-docs\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-foreign\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-server\"\\n' >> cabal.project"
+  - "printf 'packages: \"doc/tutorial\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-machines\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-conduit\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-pipes\"\\n' >> cabal.project"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/basic-auth\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/curl-mock\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/current-route\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/basic-streaming\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/db-postgres-pool\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/db-sqlite-simple\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/file-upload\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/generic\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/https\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/testing\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/structuring-apis\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/using-custom-monad\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"doc/cookbook/using-free-client\"\\n' >> cabal.project ; fi"
+  - "echo 'constraints: foundation >=0.0.14' >> cabal.project"
+  - "echo 'constraints: memory <0.14.12 || >0.14.12' >> cabal.project"
+  - "echo 'allow-newer: servant-js:base' >> cabal.project"
+  - "echo 'allow-newer: servant-pagination:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-pagination:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-multipart:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-multipart:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-auth-server:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-auth-server:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-auth-server:http-api-data' >> cabal.project"
+  - "echo 'allow-newer: servant-js:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-js:servant-foreign' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:servant-client' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:hspec' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:http-client' >> cabal.project"
+  - "echo 'reorder-goals: True' >> cabal.project"
+  - "echo 'optimization: False' >> cabal.project "
+  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
+  - touch cabal.project.local
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(cookbook-basic-auth|cookbook-basic-streaming|cookbook-curl-mock|cookbook-current-route|cookbook-db-postgres-pool|cookbook-db-sqlite-simple|cookbook-file-upload|cookbook-generic|cookbook-https|cookbook-structuring-apis|cookbook-testing|cookbook-using-custom-monad|cookbook-using-free-client|servant|servant-client|servant-client-core|servant-conduit|servant-docs|servant-foreign|servant-http-streams|servant-machines|servant-pipes|servant-server|tutorial)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+>>>>>>> dfb80faa... Add current-route recipe
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "servant/configure.ac" ]; then (cd "servant" && autoreconf -i); fi
@@ -187,6 +267,7 @@ install:
   - if [ -f "servant-pipes/configure.ac" ]; then (cd "servant-pipes" && autoreconf -i); fi
   - if [ -f "doc/cookbook/basic-auth/configure.ac" ]; then (cd "doc/cookbook/basic-auth" && autoreconf -i); fi
   - if [ -f "doc/cookbook/curl-mock/configure.ac" ]; then (cd "doc/cookbook/curl-mock" && autoreconf -i); fi
+  - if [ -f "doc/cookbook/current-route/configure.ac" ]; then (cd "doc/cookbook/current-route" && autoreconf -i); fi
   - if [ -f "doc/cookbook/basic-streaming/configure.ac" ]; then (cd "doc/cookbook/basic-streaming" && autoreconf -i); fi
   - if [ -f "doc/cookbook/db-postgres-pool/configure.ac" ]; then (cd "doc/cookbook/db-postgres-pool" && autoreconf -i); fi
   - if [ -f "doc/cookbook/db-sqlite-simple/configure.ac" ]; then (cd "doc/cookbook/db-sqlite-simple" && autoreconf -i); fi
@@ -198,6 +279,7 @@ install:
   - if [ -f "doc/cookbook/structuring-apis/configure.ac" ]; then (cd "doc/cookbook/structuring-apis" && autoreconf -i); fi
   - if [ -f "doc/cookbook/using-custom-monad/configure.ac" ]; then (cd "doc/cookbook/using-custom-monad" && autoreconf -i); fi
   - if [ -f "doc/cookbook/using-free-client/configure.ac" ]; then (cd "doc/cookbook/using-free-client" && autoreconf -i); fi
+<<<<<<< HEAD
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH} | color_cabal_output
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
   - rm  cabal.project.freeze
@@ -209,6 +291,20 @@ script:
   - echo -en 'travis_fold:end:sdist\\r'
   # Unpacking...
   - echo 'Unpacking...' && echo -en 'travis_fold:start:unpack\\r'
+=======
+  - rm -f cabal.project.freeze
+  - rm -rf .ghc.environment.* "servant"/dist "servant-client"/dist "servant-client-core"/dist "servant-http-streams"/dist "servant-docs"/dist "servant-foreign"/dist "servant-server"/dist "doc/tutorial"/dist "servant-machines"/dist "servant-conduit"/dist "servant-pipes"/dist "doc/cookbook/basic-auth"/dist "doc/cookbook/curl-mock"/dist "doc/cookbook/current-route"/dist "doc/cookbook/basic-streaming"/dist "doc/cookbook/db-postgres-pool"/dist "doc/cookbook/db-sqlite-simple"/dist "doc/cookbook/file-upload"/dist "doc/cookbook/generic"/dist "doc/cookbook/https"/dist "doc/cookbook/testing"/dist "doc/cookbook/structuring-apis"/dist "doc/cookbook/using-custom-monad"/dist "doc/cookbook/using-free-client"/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+  # test that source-distributions can be generated
+  - echo Packaging... && echo -en 'travis_fold:start:sdist\\r'
+  - ${CABAL} new-sdist all
+  - echo -en 'travis_fold:end:sdist\\r'
+  - echo Unpacking... && echo -en 'travis_fold:start:unpack\\r'
+>>>>>>> dfb80faa... Add current-route recipe
   - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
   - cd ${DISTDIR} || false
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
@@ -241,6 +337,7 @@ script:
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
+<<<<<<< HEAD
   - |
     echo "packages: ${PKGDIR_servant}" >> cabal.project
     if ! $GHCJS ; then echo "packages: ${PKGDIR_servant_client}" >> cabal.project ; fi
@@ -299,5 +396,68 @@ script:
   - if ! $GHCJS ; then ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all | color_cabal_output ; fi
   - echo -en 'travis_fold:end:haddock\\r'
 
+=======
+  - "printf 'packages: \"servant-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-client-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-client-core-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-http-streams-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-docs-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-foreign-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-server-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"tutorial-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-machines-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-conduit-*/*.cabal\"\\n' >> cabal.project"
+  - "printf 'packages: \"servant-pipes-*/*.cabal\"\\n' >> cabal.project"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-basic-auth-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-curl-mock-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-current-route-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-basic-streaming-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-db-postgres-pool-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-db-sqlite-simple-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-file-upload-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-generic-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-https-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-testing-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-structuring-apis-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-using-custom-monad-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "if [ $HCNUMVER -eq 80404 ]  ||  [ $HCNUMVER -eq 80603 ] ; then printf 'packages: \"cookbook-using-free-client-*/*.cabal\"\\n' >> cabal.project ; fi"
+  - "echo 'constraints: foundation >=0.0.14' >> cabal.project"
+  - "echo 'constraints: memory <0.14.12 || >0.14.12' >> cabal.project"
+  - "echo 'allow-newer: servant-js:base' >> cabal.project"
+  - "echo 'allow-newer: servant-pagination:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-pagination:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-multipart:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-multipart:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-auth-server:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-auth-server:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-auth-server:http-api-data' >> cabal.project"
+  - "echo 'allow-newer: servant-js:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-js:servant-foreign' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:servant' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:servant-client' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:servant-server' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:hspec' >> cabal.project"
+  - "echo 'allow-newer: servant-quickcheck:http-client' >> cabal.project"
+  - "echo 'reorder-goals: True' >> cabal.project"
+  - "echo 'optimization: False' >> cabal.project "
+  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
+  - touch cabal.project.local
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(cookbook-basic-auth|cookbook-basic-streaming|cookbook-curl-mock|cookbook-current-route|cookbook-db-postgres-pool|cookbook-db-sqlite-simple|cookbook-file-upload|cookbook-generic|cookbook-https|cookbook-structuring-apis|cookbook-testing|cookbook-using-custom-monad|cookbook-using-free-client|servant|servant-client|servant-client-core|servant-conduit|servant-docs|servant-foreign|servant-http-streams|servant-machines|servant-pipes|servant-server|tutorial)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  - echo -en 'travis_fold:end:unpack\\r'
+
+  - echo Building with tests and benchmarks... && echo -en 'travis_fold:start:build-everything\\r'
+  # build & run tests, build benchmarks
+  - ${CABAL} new-build -w ${HC} ${TEST} ${BENCH} all
+  - echo -en 'travis_fold:end:build-everything\\r'
+  - if [ "x$TEST" = "x--enable-tests" ]; then ${CABAL} new-test -w ${HC} ${TEST} ${BENCH} all; fi
+
+  - echo Haddock... && echo -en 'travis_fold:start:haddock\\r'
+  # haddock
+  - ${CABAL} new-haddock -w ${HC} ${TEST} ${BENCH} all
+
+  - echo -en 'travis_fold:end:haddock\\r'
+>>>>>>> dfb80faa... Add current-route recipe
 # REGENDATA ["--config=cabal.haskell-ci","--output=.travis.yml","cabal.project"]
 # EOF
